# Generated by Django 3.1.7 on 2021-02-23 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210223_1713'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='last_name',
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=200),
        ),
    ]
