# Generated by Django 3.1.7 on 2021-02-23 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20210223_1715'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='localgovunit',
            name='email',
        ),
        migrations.AlterField(
            model_name='participant',
            name='gender',
            field=models.CharField(choices=[('male', 'male'), ('female', 'female')], max_length=50, null=True),
        ),
    ]
