# Generated by Django 3.1.7 on 2021-02-23 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20210223_1723'),
    ]

    operations = [
        migrations.AddField(
            model_name='localgovunit',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
