# Generated by Django 3.1.7 on 2021-02-25 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20210225_2115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='gender',
            field=models.CharField(choices=[('male', 'male'), ('female', 'female')], max_length=50, null=True),
        ),
    ]
