# Generated by Django 3.1.7 on 2021-02-22 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hackaton', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hackatonchallenge',
            name='facilitator',
        ),
    ]
