# Generated by Django 3.1.7 on 2021-02-22 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackaton', '0002_remove_hackatonchallenge_facilitator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hackatonchallenge',
            name='post_image',
        ),
        migrations.AddField(
            model_name='hackatonchallenge',
            name='challenge_avatar',
            field=models.ImageField(blank=True, upload_to='challenge_avatar'),
        ),
    ]
