# Generated by Django 3.1.7 on 2021-02-22 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackaton', '0003_auto_20210222_2051'),
    ]

    operations = [
        migrations.AddField(
            model_name='hackatonchallenge',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
